name: build
on: [push, pull_request]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        gemfile:
          [
            activerecord_6.1,
            activerecord_7.2,
            activerecord_8.1,
            activerecord_master,
          ]
        ruby: ["3.3", "3.4", "jruby-9.4", "jruby-10"]
        exclude:
          - ruby: "3.4"
            gemfile: "activerecord_6.1"
          - ruby: "3.4"
            gemfile: "activerecord_7.0"
          - ruby: "3.4"
            gemfile: "activerecord_7.1"
          - ruby: "jruby-9.4"
            gemfile: "activerecord_7.1"
          - ruby: "jruby-9.4"
            gemfile: "activerecord_8.0"
          - ruby: "jruby-9.4"
            gemfile: "activerecord_8.1"
          - ruby: "jruby-9.4"
            gemfile: "activerecord_master"
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: RSpec tests
        run: bundle exec rake
      - name: StandardRB Linter
        run: bundle exec standardrb --format github --parallel
